--- #YAML:1.0
name:                Palm-ListDB-Writer
version:             1.11
abstract:            Create databases for Palm List application
license:             ~
author:              
    - Johan Vromans <jv@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
